baseURL = "https://traum-haus.netlify.app/"
languageCode = "en-us"
theme = "hugo-theme-codex"
title = "Das Traumhaus - Our House Building Journey"
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = false
[[menu.main]]
identifier = "home"
name = "home"
title = "Home"
url = "/"
weight = 2
[[menu.main]]
identifier = "blog"
name = "blog"
title = "Blog"
url = "/blog"
weight = 1
[params]
dateFormat = "Jan 2 2006"
showPageTitleInTOC = false
